name: Scheduled CIPP Update
on: 
  schedule:
    - cron: '50 11 * * 5'
    # scheduled for 11:50 UTC every Friday
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: anatawa12/fork-sync-all-branches@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
